[package]
name = "intervals-general"
version = "0.1.0"
authors = ["Scott Moeller <electronjoe@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"